trigger:
- dev

pool: 'WDKubePool'


steps:
- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'wddev-k8s service connection'
    namespace: 'test'
    command: login
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i ''s/\r$//'' ''./configure-ingress-controller-test.sh'''
    workingDirectory: "ingress/"
- task: Bash@3
  inputs:
    filePath: 'ingress/configure-ingress-controller-test.sh'
    arguments: 'test test-deploy'
    workingDirectory: "ingress/"
