trigger:
- main

pool: 'WDKubePool'


steps:

- task: Kubernetes@1
  displayName: 'kubectl login'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'wddev-k8s service connection'
    namespace: 'default'
    command: login

- task: Kubernetes@1
  displayName: 'Create Namespace'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'wddev-k8s service connection'
    command: 'apply'
    namespace: 'test'
    manifests: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: 'test'
