rbac:
  create: true
  createRole: false
  createClusterRole: false
controller:
  service:
    type: LoadBalancer
    loadBalancerIP: 10.1.0.244
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  ports:
  - port: 80
